joints:
  shoulder_pan:
    id: 1
    homing_offset: -1952
    range_min: 751
    range_max: 3471
    p_coefficient: 16 # may be original 16 is too much, set 12
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254

  shoulder_lift:
    id: 2
    homing_offset: -940
    range_min: 844
    range_max: 3208
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254

  elbow_flex:
    id: 3
    homing_offset: 490
    range_min: 862
    range_max: 3067
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254

  wrist_flex:
    id: 4
    homing_offset: -1909
    range_min: 789
    range_max: 3225
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254

  wrist_roll:
    id: 5
    homing_offset: -1955
    range_min: 0
    range_max: 4095
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254

  gripper:
    id: 6
    homing_offset: -1581
    range_min: 1523
    range_max: 3026
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254
    max_torque_limit: 500
    protection_current: 250
    overload_torque: 25
