joints:
  shoulder_pan:
    id: 1
    homing_offset: -2036
    range_min: 734
    range_max: 3458
    return_delay_time: 0    
    acceleration: 254

  shoulder_lift:
    id: 2
    homing_offset: 964
    range_min: 854
    range_max: 3256
    return_delay_time: 0   
    acceleration: 254 
  
  elbow_flex:
    id: 3
    homing_offset: 1456
    range_min: 850
    range_max: 3059
    return_delay_time: 0   
    acceleration: 254

  wrist_flex:
    id: 4
    homing_offset: -1372
    range_min: 908
    range_max: 3209
    return_delay_time: 0   
    acceleration: 254

  wrist_roll:
    id: 5
    homing_offset: -1124
    range_min: 0
    range_max: 4095
    return_delay_time: 0   
    acceleration: 254
  
  gripper:
    id: 6
    homing_offset: 782
    range_min: 1565
    range_max: 2811
    return_delay_time: 0   
    acceleration: 254
